{
gROOT->Reset();
gStyle->SetCanvasColor(10);
gStyle->SetOptFit();
gROOT->LoadMacro("TXYZ.cpp+");
gROOT->LoadMacro("TRandomGenerator.cpp+");
gROOT->LoadMacro("TElement.cpp+");
gROOT->LoadMacro("TCompound.cpp+");
gROOT->LoadMacro("TDimension.cpp+");//Dimension
gROOT->LoadMacro("TGasMixture.cpp+");
gROOT->LoadMacro("TSource.cpp+");
gROOT->LoadMacro("TPhoton.cpp+");
gROOT->LoadMacro("TTrack.cpp+");
gROOT->LoadMacro("THexagon2d.cpp+");
gROOT->LoadMacro("THexagon3d.cpp+");
gROOT->LoadMacro("TGem.cpp+");
gROOT->LoadMacro("TReadout.cpp+");
gROOT->LoadMacro("TDetector.cpp+");
gROOT->LoadMacro("TCluster.cpp+");
gROOT->LoadMacro("TMDP.cpp+");
gROOT->LoadMacro("FastSimulator.cxx+");
gROOT->LoadMacro("Astro.cxx+");

gROOT->LoadMacro("TTreeAnalysis.cpp+");
gROOT->LoadMacro("TExperiment.cpp+");
gROOT->LoadMacro("Validation2.cpp+");
gROOT->LoadMacro("Validation.cpp+");
gROOT->LoadMacro("ResultScan.cpp+");
}
 
